# Generated by Django 5.1.7 on 2025-04-21 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="submissions.submission",
            ),
        ),
    ]
