# Generated by Django 5.1.7 on 2025-04-25 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_initial"),
        ("reviews", "0002_initial"),
        ("submissions", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="core_activities",
                to="reviews.review",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="core_activities",
                to="submissions.submission",
            ),
        ),
    ]
