# Generated by Django 5.1.7 on 2025-04-21 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submissions", "0001_initial"),
        ("versions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="versions.version",
            ),
        ),
        migrations.AddField(
            model_name="submissionimage",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="submissions.submission",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="technologies",
            field=models.ManyToManyField(to="submissions.technology"),
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("user", "version", "day_number")},
        ),
    ]
