# Generated by Django 5.1.7 on 2025-04-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="cloudinary_public_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
