# Generated by Django 5.1.7 on 2025-04-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0003_submission_cloudinary_public_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submissionimage",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="submissionimage",
            name="cloudinary_public_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
