# Generated by Django 5.1.7 on 2025-04-30 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_rename_helpful_count_review_helpful_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"default_manager_name": "objects", "ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
